version: '3.8'

services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: odoo

volumes:
  postgres-data: