version: '3.8'

services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.devcontainer:/workspaces/.devcontainer
      - ../.vscode:/workspaces/.vscode
      - ~/.gitconfig:/home/vscode/.gitconfig
      - ~/.ssh/id_rsa:/home/vscode/.ssh/id_rsa
    command: sleep infinity
    network_mode: service:postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: odoo

volumes:
  postgres-data: